<?php

namespace App\Support;

/**
 * Single-page A4 receipt PDF using built-in Helvetica fonts.
 */
final class PlainPdf
{
    /**
     * @param  array{
     *     reference: string,
     *     provider_reference: string,
     *     rrn: string,
     *     vendor: string,
     *     merchant: string,
     *     service: string,
     *     amount: string,
     *     status: string,
     *     provider_status: string,
     *     provider_message: string,
     *     datetime: string,
     *     aadhaar: string
     * }  $receipt
     */
    public static function receipt(array $receipt): string
    {
        $badge = self::badgeFor($receipt['status']);
        $ops = [];

        self::fill($ops, 0.114, 0.306, 0.847, 0, 760, 595, 82);
        self::fill($ops, 0.075, 0.220, 0.690, 0, 760, 595, 4);
        self::fill($ops, 1, 1, 1, 36, 782, 34, 34);
        self::text($ops, 'FP', 42, 793, 12, true, [0.114, 0.306, 0.847]);
        self::text($ops, 'FinPe', 82, 800, 20, true, [1, 1, 1]);
        self::text($ops, 'Admin Gateway', 82, 784, 9, false, [0.82, 0.89, 1]);

        self::text($ops, 'AePS Transaction Receipt', 36, 728, 16, true, [0.09, 0.14, 0.22]);
        self::drawBadge($ops, $badge[0], 430, 720, 130, 24, $badge[1], $badge[2]);

        self::card($ops, 36, 648, 252, 58);
        self::text($ops, 'AMOUNT', 48, 684, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, $receipt['amount'], 48, 662, 16, true, [0.09, 0.14, 0.22]);

        self::card($ops, 304, 648, 255, 58);
        self::text($ops, 'FINPE REFERENCE', 316, 684, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, $receipt['reference'], 316, 662, 12, true, [0.114, 0.306, 0.847]);

        $y = 628;
        $y = self::section($ops, $y, 'Transaction Details', [
            ['Service', $receipt['service']],
            ['FinPe reference', $receipt['reference']],
            ['Aadhaar', $receipt['aadhaar']],
            ['Status', $receipt['status']],
            ['Date/time', $receipt['datetime']],
        ]);
        $y = self::section($ops, $y, 'Merchant & Vendor Details', [
            ['Vendor', $receipt['vendor']],
            ['Merchant', $receipt['merchant']],
        ]);
        self::section($ops, $y, 'Provider Details', [
            ['Provider reference', $receipt['provider_reference'], true],
            ['RRN', $receipt['rrn'], true],
            ['Provider status', $receipt['provider_status']],
            ['Provider message', $receipt['provider_message']],
        ]);

        self::stroke($ops, 0.82, 0.86, 0.90, 36, 48, 523);
        self::text($ops, 'Generated by FinPe', 36, 30, 9, false, [0.39, 0.45, 0.55]);

        return self::document(implode("\n", $ops));
    }

    /**
     * @param  array{
     *     reference: string,
     *     merchant_ref: string,
     *     provider_reference: string,
     *     vendor: string,
     *     provider: string,
     *     beneficiary_name: string,
     *     account: string,
     *     ifsc: string,
     *     bank: string,
     *     mobile: string,
     *     location: string,
     *     payment_mode: string,
     *     payment_purpose: string,
     *     amount: string,
     *     charge: string,
     *     total_debited: string,
     *     status: string,
     *     provider_message: string,
     *     created_at: string,
     *     updated_at: string
     * }  $receipt
     */
    public static function payoutReceipt(array $receipt): string
    {
        $badge = self::badgeFor($receipt['status']);
        $ops = [];

        self::fill($ops, 0.114, 0.306, 0.847, 0, 760, 595, 82);
        self::fill($ops, 0.075, 0.220, 0.690, 0, 760, 595, 4);
        self::fill($ops, 1, 1, 1, 36, 782, 34, 34);
        self::text($ops, 'FP', 42, 793, 12, true, [0.114, 0.306, 0.847]);
        self::text($ops, 'FinPe', 82, 800, 20, true, [1, 1, 1]);
        self::text($ops, 'Payout receipt', 82, 784, 9, false, [0.82, 0.89, 1]);

        self::text($ops, 'Money Transfer Receipt', 36, 728, 16, true, [0.09, 0.14, 0.22]);
        self::drawBadge($ops, $badge[0], 430, 720, 130, 24, $badge[1], $badge[2]);

        self::card($ops, 36, 648, 168, 58);
        self::text($ops, 'PAYOUT AMOUNT', 48, 684, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, $receipt['amount'], 48, 662, 14, true, [0.09, 0.14, 0.22]);

        self::card($ops, 216, 648, 168, 58);
        self::text($ops, 'CHARGE', 228, 684, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, $receipt['charge'], 228, 662, 14, true, [0.09, 0.14, 0.22]);

        self::card($ops, 396, 648, 163, 58);
        self::text($ops, 'TOTAL DEBITED', 408, 684, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, $receipt['total_debited'], 408, 662, 12, true, [0.09, 0.14, 0.22]);

        $y = 628;
        $y = self::section($ops, $y, 'Beneficiary Details', [
            ['Name', $receipt['beneficiary_name']],
            ['Account', $receipt['account'], true],
            ['IFSC', $receipt['ifsc']],
            ['Bank', $receipt['bank']],
            ['Mobile', $receipt['mobile'], true],
            ['Location', $receipt['location']],
        ], 20);
        $y = self::section($ops, $y, 'Transaction Details', [
            ['FinPe reference', $receipt['reference'], true],
            ['Merchant reference', $receipt['merchant_ref']],
            ['Payment mode', $receipt['payment_mode']],
            ['Payment purpose', $receipt['payment_purpose']],
            ['Vendor', $receipt['vendor']],
            ['Status', $receipt['status']],
            ['Created', $receipt['created_at']],
            ['Updated', $receipt['updated_at']],
        ], 20);
        self::section($ops, $y, 'Provider Details', [
            ['Provider', $receipt['provider']],
            ['Provider reference', $receipt['provider_reference'], true],
            ['Provider message', $receipt['provider_message']],
        ], 20);

        self::stroke($ops, 0.82, 0.86, 0.90, 36, 48, 523);
        self::text($ops, 'Generated by FinPe · Admin Gateway', 36, 30, 9, false, [0.39, 0.45, 0.55]);

        return self::document(implode("\n", $ops));
    }

    /**
     * @param  list<array{0: string, 1: string, 2: string, 3: string}>  $parameters
     * @param  list<string>  $exampleLines
     */
    public static function apiDocumentation(array $parameters, array $exampleLines): string
    {
        $ops = [];
        self::fill($ops, 0.114, 0.306, 0.847, 0, 790, 595, 52);
        self::text($ops, 'FinPe', 36, 808, 16, true, [1, 1, 1]);
        self::text($ops, 'AePS API documentation', 36, 748, 14, true, [0.09, 0.14, 0.22]);
        self::text($ops, 'Transaction request', 36, 722, 12, true, [0.09, 0.14, 0.22]);
        self::text($ops, 'POST /api/v1/aeps/transactions', 36, 704, 10, false, [0.20, 0.24, 0.30]);
        self::text($ops, 'Request parameters', 36, 678, 12, true, [0.09, 0.14, 0.22]);

        $y = 656;
        self::text($ops, 'Field', 36, $y, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, 'Type', 168, $y, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, 'Required', 230, $y, 8, true, [0.39, 0.45, 0.55]);
        self::text($ops, 'Description', 310, $y, 8, true, [0.39, 0.45, 0.55]);
        $y -= 8;
        self::stroke($ops, 0.82, 0.86, 0.90, 36, $y, 523);
        $y -= 16;

        foreach ($parameters as $row) {
            $highlight = $row[0] === 'aadhaarNumber';
            self::text($ops, $row[0], 36, $y, 9, $highlight, $highlight ? [0.114, 0.306, 0.847] : [0.09, 0.14, 0.22]);
            self::text($ops, $row[1], 168, $y, 9, false, [0.20, 0.24, 0.30]);
            self::text($ops, $row[2], 230, $y, 9, $highlight, $highlight ? [0.114, 0.306, 0.847] : [0.20, 0.24, 0.30]);
            self::text($ops, $row[3], 310, $y, 9, false, [0.20, 0.24, 0.30]);
            $y -= 16;
        }

        $y -= 8;
        self::text($ops, 'JSON example', 36, $y, 12, true, [0.09, 0.14, 0.22]);
        $y -= 18;
        foreach ($exampleLines as $line) {
            $bold = str_contains($line, 'aadhaarNumber');
            self::text($ops, $line, 36, $y, 9, $bold, $bold ? [0.114, 0.306, 0.847] : [0.20, 0.24, 0.30]);
            $y -= 13;
        }

        self::text($ops, 'Generated by FinPe', 36, 28, 9, false, [0.39, 0.45, 0.55]);

        return self::document(implode("\n", $ops));
    }

    /**
     * @param  list<string>  $ops
     * @param  list<array{0: string, 1: string, 2?: bool}>  $rows
     */
    private static function section(array &$ops, float $y, string $title, array $rows, int $rowHeight = 22): float
    {
        $lines = [];
        foreach ($rows as $row) {
            $parts = str_split(self::plain($row[1]), 58);
            if ($parts === []) {
                $parts = ['-'];
            }
            foreach ($parts as $index => $part) {
                $lines[] = [$index === 0 ? $row[0] : '', $part, ! empty($row[2])];
            }
        }
        $height = 26 + (count($lines) * $rowHeight) + 8;
        $top = $y;
        $bottom = $top - $height;

        self::strokeRect($ops, 36, $bottom, 523, $height);
        self::fill($ops, 0.94, 0.96, 0.98, 36.5, $top - 26, 522, 25.5);
        self::text($ops, $title, 48, $top - 18, 10, true, [0.09, 0.14, 0.22]);

        $rowY = $top - 26;
        foreach ($lines as $row) {
            $rowY -= $rowHeight;
            if (! empty($row[2])) {
                self::fill($ops, 0.93, 0.96, 1, 37, $rowY - 4, 521, $rowHeight);
            }
            self::text($ops, $row[0], 48, $rowY + 2, 9, false, [0.39, 0.45, 0.55]);
            self::text($ops, $row[1], 230, $rowY + 2, 9, ! empty($row[2]), [0.09, 0.14, 0.22]);
        }

        return $bottom - 14;
    }

    /**
     * @param  list<string>  $ops
     * @param  array{float, float, float}  $fill
     * @param  array{float, float, float}  $ink
     */
    private static function drawBadge(array &$ops, string $label, float $x, float $y, float $w, float $h, array $fill, array $ink): void
    {
        self::fill($ops, $fill[0], $fill[1], $fill[2], $x, $y, $w, $h);
        self::text($ops, $label, $x + 16, $y + 7, 10, true, $ink);
    }

    /**
     * @return array{0: string, 1: array{float, float, float}, 2: array{float, float, float}}
     */
    private static function badgeFor(string $status): array
    {
        $status = strtolower(str_replace(' ', '_', trim($status)));
        if ($status === 'success') {
            return ['SUCCESS', [0.86, 0.95, 0.88], [0.08, 0.40, 0.22]];
        }
        if (in_array($status, ['failed', 'validation_failed', 'provider_error'], true)) {
            return ['FAILED', [0.98, 0.90, 0.90], [0.60, 0.12, 0.12]];
        }

        return ['PENDING', [0.99, 0.95, 0.84], [0.52, 0.34, 0.05]];
    }

    /**
     * @param  list<string>  $ops
     */
    private static function card(array &$ops, float $x, float $y, float $w, float $h): void
    {
        self::fill($ops, 0.97, 0.98, 0.99, $x, $y, $w, $h);
        self::strokeRect($ops, $x, $y, $w, $h);
    }

    /**
     * @param  list<string>  $ops
     */
    private static function fill(array &$ops, float $r, float $g, float $b, float $x, float $y, float $w, float $h): void
    {
        $ops[] = sprintf('%.3F %.3F %.3F rg', $r, $g, $b);
        $ops[] = sprintf('%.2F %.2F %.2F %.2F re f', $x, $y, $w, $h);
    }

    /**
     * @param  list<string>  $ops
     */
    private static function strokeRect(array &$ops, float $x, float $y, float $w, float $h): void
    {
        $ops[] = '0.820 0.860 0.900 RG';
        $ops[] = '0.8 w';
        $ops[] = sprintf('%.2F %.2F %.2F %.2F re S', $x, $y, $w, $h);
    }

    /**
     * @param  list<string>  $ops
     */
    private static function stroke(array &$ops, float $r, float $g, float $b, float $x1, float $y, float $width): void
    {
        $ops[] = sprintf('%.3F %.3F %.3F RG', $r, $g, $b);
        $ops[] = '0.6 w';
        $ops[] = sprintf('%.2F %.2F m %.2F %.2F l S', $x1, $y, $x1 + $width, $y);
    }

    /**
     * @param  list<string>  $ops
     * @param  array{float, float, float}  $color
     */
    private static function text(array &$ops, string $value, float $x, float $y, float $size, bool $bold, array $color): void
    {
        $font = $bold ? '/F2' : '/F1';
        $ops[] = 'BT';
        $ops[] = sprintf('%.3F %.3F %.3F rg', $color[0], $color[1], $color[2]);
        $ops[] = $font.' '.sprintf('%.1F', $size).' Tf';
        $ops[] = sprintf('1 0 0 1 %.2F %.2F Tm', $x, $y);
        $ops[] = '('.self::escape($value).') Tj';
        $ops[] = 'ET';
    }

    private static function document(string $stream): string
    {
        $objects = [
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj\n",
            "4 0 obj\n<< /Length ".strlen($stream)." >>\nstream\n{$stream}\nendstream\nendobj\n",
            "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
            "6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n",
        ];

        $pdf = "%PDF-1.4\n";
        $offsets = [0];
        foreach ($objects as $object) {
            $offsets[] = strlen($pdf);
            $pdf .= $object;
        }
        $xref = strlen($pdf);
        $pdf .= "xref\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";
        foreach (array_slice($offsets, 1) as $offset) {
            $pdf .= sprintf("%010d 00000 n \n", $offset);
        }
        $pdf .= "trailer\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xref}\n%%EOF";

        return $pdf;
    }

    private static function plain(string $value): string
    {
        return preg_replace('/[^\x20-\x7E]/', ' ', $value) ?? '';
    }

    private static function escape(string $value): string
    {
        $value = preg_replace('/[^\x20-\x7E]/', ' ', $value) ?? '';
        $value = str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $value);

        return $value;
    }
}
